  customCSS = ["css/custom.css"]

baseURL = "https://stellar-pudding-178dd4.netlify.app/"
languageCode = "ja-jp"
title = "極選アダルトNAVI"
theme = "masu-theme"
enableRobotsTXT = true

[pagination]
  pagerSize = 30        # ← 旧 paginate を置き換え

[markup]

